CAPN/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/contacts/')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
]

contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product_mnt_create', views.Product_mntCreateView.as_view(), name='product_mnt_create'),
    path('contact_mnt_create', views.Contact_mntCreateView.as_view(), name='contact_mnt_create'),
    path('part_numberQuery', views.part_numberQuery, name='part_numberQuery'),
    path('apiQuery', views.apiQuery, name='apiQuery'),
    path('data_upload', views.DataUploadView.as_view(), name='data_upload'),
]

contacts/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):
    catalog_number = models.CharField(max_length=20, unique=True)
    style_number = models.CharField(max_length=20, blank=True, unique=True)
    contact = models.ForeignKey('contacts.Contact', on_delete=models.CASCADE)

    def __str__(self):
        return self.catalog_number

class Contact(models.Model):
    name = models.CharField(max_length=200,unique=True)
    phone = models.CharField(max_length=500, blank=True)
    email = models.EmailField(blank=True)
    link = models.URLField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Product_mnt(models.Model):
    pid = models.IntegerField(blank=True,null=True)
    catalog_number = models.CharField(max_length=20, unique=True)
    style_number = models.CharField(max_length=20, blank=True, unique=True)
    contact = models.ForeignKey('contacts.Contact', on_delete=models.CASCADE)
    note = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.catalog_number

    def get_absolute_url(self):
        return reverse('contacts:index')

class Contact_mnt(models.Model):
    pid = models.IntegerField(blank=True,null=True)
    name = models.CharField(max_length=200,unique=True)
    phone = models.CharField(max_length=500, blank=True)
    email = models.EmailField(blank=True)
    link = models.URLField(blank=True)
    note = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('contacts:index')

contacts/forms.py
from django import forms

class DataUploadForm(forms.Form):
    contact_file = forms.FileField(help_text='File must have these exact four columns: name, phone, email, link', required=False)
    product_file = forms.FileField(help_text='File must have these exact three columns: catalog_number, style_number, contact_name', required=False)

contacts/views.py
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.http import JsonResponse
from django.db.models import Q
from contacts.models import Product,Product_mnt,Contact,Contact_mnt
import pandas as pd
from django.db import IntegrityError, transaction
from django.shortcuts import render
from contacts.forms import DataUploadForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

class IndexView(TemplateView):
    template_name = 'contacts/index.html'

class Product_mntCreateView(CreateView):
    model = Product_mnt
    fields = ('catalog_number','style_number','contact','note')
    template_name = 'contacts/mnt_create.html'

    def get_initial(self):
        c = self.request.GET.get('c','')
        initial = super(Product_mntCreateView, self).get_initial()
        initial = initial.copy()
        if c:
            prod = Product.objects.get(catalog_number=c)
            initial['pid'] = prod.pk
            initial['catalog_number'] = prod.catalog_number
            initial['style_number'] = prod.style_number
            initial['contact'] = prod.contact
        return initial

class Contact_mntCreateView(CreateView):
    model = Contact_mnt
    fields = ('name','phone','email','link','note')
    template_name = 'contacts/mnt_create.html'

    def get_initial(self):
        c = self.request.GET.get('c','')
        initial = super(Contact_mntCreateView, self).get_initial()
        initial = initial.copy()
        if c:
            cont = Contact.objects.get(name=c)
            initial['pid'] = cont.pk
            initial['name'] = cont.name
            initial['phone'] = cont.phone
            initial['email'] = cont.email
            initial['link'] = cont.link
        return initial

####################
### Part # Query ###
####################
def part_numberQuery(request):
    part_num = request.GET.get('q')
    timestamp = request.GET.get('t')
    product_result = {'t':timestamp,'result':list(Product.objects.filter(
        Q(catalog_number__istartswith=part_num) |
        Q(style_number__istartswith=part_num)).select_related('contact').values(
            'catalog_number',
            'style_number',
            'contact__name',
            'contact__phone',
            'contact__email',
            'contact__link'))[:42]}
    return JsonResponse(product_result, safe=True)

####################
### API Query ###
####################
@csrf_exempt
def apiQuery(request):
    part_num = request.GET.get('q')
    product_result = {'result':list(Product.objects.filter(
        Q(catalog_number=part_num) |
        Q(style_number=part_num)).select_related('contact').values(
            'catalog_number',
            'style_number',
            'contact__name',
            'contact__phone',
            'contact__email',
            'contact__link'))}
    return JsonResponse(product_result, safe=True)

##############################
### Mass Update            ###
##############################

@method_decorator(login_required, name='dispatch')
class DataUploadView(generic.FormView):
    template_name = 'contacts/data_upload.html'
    form_class = DataUploadForm
    success_url = '/contacts/'

    def form_valid(self, form):
        data = ''
        contact_sheet = form.cleaned_data.get('contact_file')
        if contact_sheet:
            cdf = pd.read_excel(contact_sheet)
            headers = set(list(cdf))
            model_fields = set(['name','phone','email','link'])
            if headers != model_fields:
                data += 'Contact headers are not correct<br>'
                return render(self.request,'contacts/data_upload.html',
                    {'data':data})
            else:
                with transaction.atomic():
                    for row in cdf.itertuples():
                        obj, created = Contact.objects.update_or_create(
                            name = row.name,
                            defaults = {
                                'phone':row.phone,
                                'email':row.email,
                                'link':row.link,
                            }
                        )
                data += 'Contact data successfully added<br>'
        else:
            data += 'No contact data<br>'

        product_sheet = form.cleaned_data.get('product_file')
        if product_sheet:
            pdf = pd.read_excel(product_sheet)
            headers = set(list(pdf))
            model_fields = set(['catalog_number','style_number','contact_name'])
            if headers != model_fields:
                data += 'Product headers are not correct<br>'
                return render(self.request,'contacts/data_upload.html',
                    {'data':data})
            else:
                with transaction.atomic():
                    for row in pdf.itertuples():
                        try:
                            contact = Contact.objects.get(name=row.contact_name)
                            obj, created = Product.objects.update_or_create(
                                catalog_number = row.catalog_number,
                                defaults = {
                                    'style_number':row.style_number,
                                    'contact':contact,
                                }
                            )
                        except IntegrityError:
                            continue
                data += 'Product data successfully added<br>'
        else:
            data += 'No product data<br>'

        return render(self.request,'contacts/data_upload.html',
                    {'data':data})

contacts/templates/contacts/contact_mnt_create.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<title>CAPN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% block head %}{% endblock %}
</head>

<body>
    <form class="w3-form" method="post">
    {% csrf_token %}
    <fieldset>
    <table class="w3-table">
        {{ form.as_table }}
    </table>
    <input class="w3-button w3-black" type="submit" value="Create" />
    <a class="w3-button w3-black" href="{% url 'contacts:index' %}">Cancel</a>
    </fieldset>
    </form>
</body>
</html>

contacts/templates/contacts/data_upload.html
<!DOCTYPE html>
<html>
<head>
	<title>CAPN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>
{% if form %}
<div class="w3-panel">
<form class="w3-form" method="post" enctype="multipart/form-data" action = "{% url 'contacts:data_upload' %}">

    {% csrf_token %}

    {{ form.as_p }}

    <input class="w3-btn w3-black" type="submit" value="Upload">

</form>
</div>
{% endif %}
{% if data %}
<div>
    {{ data|safe }}
</div>
{% endif %}

</body>
</html>

contacts/templates/contacts/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<title>CAPN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'contacts/hoja.css' %}"/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% block head %}{% endblock %}
</head>

<body>
    <div class="w3-panel">
        <div class="w3-center">
            <img src="{% static 'contacts/Eaton_Corporation_logo.svg' %}" alt="EATON" width="512" height="143">
        </div>
    </div>
    <div class="w3-panel">
        <div class="w3-center">
            <input type="text" id="part_number_search" placeholder="Search...">
        </div>
    </div>
    <div class="w3-panel w3-center">
        <a class="web-search w3-button w3-circle w3-yellow w3-hide"
            data-link="https://www.google.com/search?safe=active&q=eaton+" target="_blank">google</a>
        <a class="web-search w3-button w3-circle w3-red w3-hide"
            data-link="https://duckduckgo.com/?q=eaton+" target="_blank">duck</a>
        <a class="web-search w3-button w3-circle w3-blue w3-hide"
            data-link="https://www.bing.com/search?q=eaton+" target="_blank">bing</a>
        <a class="web-search w3-button w3-circle w3-purple w3-hide"
            data-link="https://search.yahoo.com/search?p=eaton+" target="_blank">yahoo</a>
    </div>
    <div class="w3-panel" id="part_number_results">
        <div class="w3-center">
            <div id="hojaya">
                <div class="hoja">CAPN</div>
            </div>
        </div>
    </div>

	{% block content %}{% endblock content %}
</body>

<script>

$( document ).ready(function() {

var part_number_div = document.getElementById("part_number_results");
var $in = $('#part_number_search')

function part_numberDisplay(json) {
    part_number_div.innerHTML = "";
    var $table = $('<table>')
        .prop("id","result_table")
        .data( "t", json.t )
        .addClass("w3-table-all")
        .addClass("w3-hoverable")
        .appendTo('#part_number_results');
    $table.append(
        $('<th>').text('Catalog Number'),
        $('<th>').text('Style Number'),
        $('<th>').html('<a class="w3-button w3-circle w3-black" href="{% url "contacts:product_mnt_create" %}">+</a>'),
        $('<th>').text('Support'),
        $('<th>').text('Phone'),
        $('<th>').text('Email'),
        $('<th>').html('<a class="w3-button w3-circle w3-black" href="{% url "contacts:contact_mnt_create" %}">+</a>')

    );
    $.each(json.result, function(i, item) {
        if (item.contact__link === "#" || item.contact__link === "") {
        var a = $('<a>');
        } else {
            var a = $('<a>', {href:item.contact__link,target:"_blank"});
        }
        a.text(item.contact__name);
        catalog_index = item.catalog_number.indexOf($in.val());console.log(catalog_index);
        if (catalog_index >= 0) {
            catalogHTML = item.catalog_number.substring(0,catalog_index) +
                '<span style="background-color:yellow">' +
                item.catalog_number.substring(catalog_index,catalog_index+$in.val().length) +
                "</span>" +
                item.catalog_number.substring(catalog_index + $in.val().length);
        } else {
            catalogHTML = item.catalog_number;
        }
        style_index = item.style_number.indexOf($('#part_number_search').val())
        if (style_index >= 0) {
            styleHTML = item.style_number.substring(0,style_index) +
                '<span style="background-color:yellow">' +
                item.style_number.substring(style_index,style_index+$in.val().length) +
                "</span>" +
                item.style_number.substring(style_index + $in.val().length);
        } else {
            styleHTML = item.style_number;
        }
        var $tr = $('<tr>').append(
            $('<td>').html(catalogHTML),
            $('<td>').html(styleHTML),
            $('<td>').html('<a class="w3-button w3-circle w3-black" href="{% url "contacts:product_mnt_create" %}?c='+item.catalog_number+'">&#x270E;</a>'),
            $('<td>').append(a),
            $('<td>').html(item.contact__phone),
            $('<td>').text(item.contact__email),
            $('<td>').html('<a class="w3-button w3-circle w3-black" href="{% url "contacts:contact_mnt_create" %}?c='+item.contact__name+'">&#x270E;</a>')
        ).appendTo($table);
    });
}

function part_numberQuery(element) {
    element.value = element.value.toUpperCase()
	if (element.value.length > 2) {
        $("a.web-search").each(function() {
            $this = $(this);
            $this.prop("href", $this.data("link") + element.value);
        });
        $("a.web-search").removeClass("w3-hide");
        $.get("{% url 'contacts:part_numberQuery' %}"+"?q="+element.value+"&t="+$.now(), function(data,status) {console.log($('#result_table').data("t"));
            $time_stamp = $('#result_table').data("t")
            if (data.t > $time_stamp || typeof $time_stamp === "undefined") {
                part_numberDisplay(data);
            }
        });
	} else {
	    $("a.web-search").addClass("w3-hide");
	    part_number_div.innerHTML = '<div id="hojaya"><div class="hoja">CAPN</div></div>';
	}
}

function addInputCallback(search_input, callback, delay) {
    var timer = null;
    search_input.onkeyup = function(e) {
        if (timer) {
            window.clearTimeout(timer);
        }
        timer = window.setTimeout( function() {
            timer = null;
            callback(e.target);
        }, delay );
    };
    search_input = null;
}

addInputCallback( document.getElementById("part_number_search"), part_numberQuery, 500 );

});
</script>
</html>

contacts/templates/contacts/mnt_create.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<title>CAPN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% block head %}{% endblock %}
</head>

<body>
    <form class="w3-form" method="post">
    {% csrf_token %}
    <fieldset>
    <table class="w3-table">
        {{ form.as_table }}
    </table>
    <input class="w3-button w3-black" type="submit" value="Create" />
    <a class="w3-button w3-black" href="{% url 'contacts:index' %}">Cancel</a>
    </fieldset>
    </form>
</body>
</html>

contacts/templates/contacts/product_mnt_create.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<title>CAPN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% block head %}{% endblock %}
</head>

<body>
    <form class="w3-form" method="post">
    {% csrf_token %}
    <fieldset>
    <table class="w3-table">
        {{ form.as_table }}
    </table>
    <input class="w3-button w3-black" type="submit" value="Create" />
    <a class="w3-button w3-black" href="{% url 'contacts:index' %}">Cancel</a>
    </fieldset>
    </form>
</body>
</html>